name: Generate Coverage

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pythonUtils
          environment-file: env.yml
          auto-activate-base: false
          auto-update-conda: true
      
      - name: Install coverage
        run: conda install -c conda-forge coverage

      - name: Run tests coverage
        run: make generate_coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
